name: Feature request
description: Suggest a new feature for MapRoulette
labels: [enhancement]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see?
      description: A clear description of the feature you'd like to add to MapRoulette
    validations:
      required: true

  - type: textarea
    id: feature-value
    attributes:
      label: Why is this useful?
      description: How would this feature help you or other MapRoulette users?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other details that might help us understand your request (optional)
