/**
 * Central export file for generated API types
 *
 * This file is AUTO-GENERATED by scripts/generate-type-exports.js
 * DO NOT EDIT MANUALLY - your changes will be overwritten
 *
 * To regenerate: npm run generate:api-types
 */

import type { components, paths } from './typesFromApi'

// ============================================================================
// Main Entity Types
// ============================================================================

export type ElementCreate = components['schemas']['ElementCreate']
export type ElementTagChange = components['schemas']['ElementTagChange']
export type ElementUpdate = components['schemas']['ElementUpdate']
export type Keyword = components['schemas']['Keyword']
export type OSMChange = components['schemas']['OSMChange']
export type OSMChangeSubmission = components['schemas']['OSMChangeSubmission']
export type OSMType = components['schemas']['OSMType']
export type Project = components['schemas']['Project']
export type PublicOSMUser = components['schemas']['PublicOSMUser']
export type PublicUser = components['schemas']['PublicUser']
export type PublicUserSettings = components['schemas']['PublicUserSettings']
export type TagChange = components['schemas']['TagChange']
export type TagChangeResult = components['schemas']['TagChangeResult']
export type TagChangeSubmission = components['schemas']['TagChangeSubmission']
export type TaskBundle = components['schemas']['TaskBundle']

// ============================================================================
// Model Types (org.maproulette.*)
// ============================================================================

// export type StatusMessage = components['schemas']['org.maproulette.exception.StatusMessage']
// export type ChallengeCreation =
//   components['schemas']['org.maproulette.framework.model.ChallengeCreation']
// export type ChallengeExtra = components['schemas']['org.maproulette.framework.model.ChallengeExtra']
// export type ChallengeGeneral =
//   components['schemas']['org.maproulette.framework.model.ChallengeGeneral']
// export type ChallengePriority =
//   components['schemas']['org.maproulette.framework.model.ChallengePriority']
// export type ClusteredPoint = components['schemas']['org.maproulette.framework.model.ClusteredPoint']
// export type Comment = components['schemas']['org.maproulette.framework.model.Comment']
// export type Grant = components['schemas']['org.maproulette.framework.model.Grant']
// export type Task = components['schemas']['org.maproulette.framework.model.Task']
// export type TaskClusterSummary =
//   components['schemas']['org.maproulette.framework.model.TaskClusterSummary']
// export type TaskMarker = components['schemas']['org.maproulette.framework.model.TaskMarker']
// export type TaskMarkerLocation =
//   components['schemas']['org.maproulette.framework.model.TaskMarkerLocation']
// export type TaskMarkerResponse =
//   components['schemas']['org.maproulette.framework.model.TaskMarkerResponse']

// export type User = components['schemas']['org.maproulette.framework.model.User']
// export type UserNotification =
//   components['schemas']['org.maproulette.framework.model.UserNotification']

// ============================================================================
// Re-export for advanced usage
// ============================================================================

export type { components, paths }
