/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppLearnRouteImport } from './routes/_app.learn'
import { Route as AppDonateRouteImport } from './routes/_app.donate'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app.tasks.$taskId'
import { Route as AppChallengesChallengeIdRouteImport } from './routes/_app.challenges.$challengeId'
import { Route as AppBrowseChallengesRouteImport } from './routes/_app.browse.challenges'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppDonateRoute = AppDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesChallengeIdRoute =
  AppChallengesChallengeIdRouteImport.update({
    id: '/challenges/$challengeId',
    path: '/challenges/$challengeId',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrowseChallengesRoute = AppBrowseChallengesRouteImport.update({
  id: '/browse/challenges',
  path: '/browse/challenges',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AppDashboardRoute
  '/donate': typeof AppDonateRoute
  '/learn': typeof AppLearnRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/browse/challenges': typeof AppBrowseChallengesRoute
  '/challenges/$challengeId': typeof AppChallengesChallengeIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AppDashboardRoute
  '/donate': typeof AppDonateRoute
  '/learn': typeof AppLearnRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/browse/challenges': typeof AppBrowseChallengesRoute
  '/challenges/$challengeId': typeof AppChallengesChallengeIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/donate': typeof AppDonateRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/browse/challenges': typeof AppBrowseChallengesRoute
  '/_app/challenges/$challengeId': typeof AppChallengesChallengeIdRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/donate'
    | '/learn'
    | '/settings'
    | '/'
    | '/browse/challenges'
    | '/challenges/$challengeId'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/donate'
    | '/learn'
    | '/settings'
    | '/'
    | '/browse/challenges'
    | '/challenges/$challengeId'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/donate'
    | '/_app/learn'
    | '/_app/settings'
    | '/_app/'
    | '/_app/browse/challenges'
    | '/_app/challenges/$challengeId'
    | '/_app/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donate': {
      id: '/_app/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof AppDonateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenges/$challengeId': {
      id: '/_app/challenges/$challengeId'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof AppChallengesChallengeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/challenges': {
      id: '/_app/browse/challenges'
      path: '/browse/challenges'
      fullPath: '/browse/challenges'
      preLoaderRoute: typeof AppBrowseChallengesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDonateRoute: typeof AppDonateRoute
  AppLearnRoute: typeof AppLearnRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBrowseChallengesRoute: typeof AppBrowseChallengesRoute
  AppChallengesChallengeIdRoute: typeof AppChallengesChallengeIdRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDonateRoute: AppDonateRoute,
  AppLearnRoute: AppLearnRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBrowseChallengesRoute: AppBrowseChallengesRoute,
  AppChallengesChallengeIdRoute: AppChallengesChallengeIdRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
