/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppTasksRouteRouteImport } from './routes/_app/tasks/route'
import { Route as AppChallengesIndexRouteImport } from './routes/_app/challenges/index'
import { Route as AppTasksTaskIdIndexRouteImport } from './routes/_app/tasks/[$taskId]/index'
import { Route as AppChallengesChallengeIdIndexRouteImport } from './routes/_app/challenges/[$challengeId]/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksRouteRoute = AppTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChallengesIndexRoute = AppChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksTaskIdIndexRoute = AppTasksTaskIdIndexRouteImport.update({
  id: '/$taskId/',
  path: '/$taskId/',
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppChallengesChallengeIdIndexRoute =
  AppChallengesChallengeIdIndexRouteImport.update({
    id: '/challenges/$challengeId/',
    path: '/challenges/$challengeId/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/tasks': typeof AppTasksRouteRouteWithChildren
  '/account': typeof AppAccountRoute
  '/': typeof AppIndexRoute
  '/challenges': typeof AppChallengesIndexRoute
  '/challenges/$challengeId': typeof AppChallengesChallengeIdIndexRoute
  '/tasks/$taskId': typeof AppTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/tasks': typeof AppTasksRouteRouteWithChildren
  '/account': typeof AppAccountRoute
  '/': typeof AppIndexRoute
  '/challenges': typeof AppChallengesIndexRoute
  '/challenges/$challengeId': typeof AppChallengesChallengeIdIndexRoute
  '/tasks/$taskId': typeof AppTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/tasks': typeof AppTasksRouteRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/': typeof AppIndexRoute
  '/_app/challenges/': typeof AppChallengesIndexRoute
  '/_app/challenges/$challengeId/': typeof AppChallengesChallengeIdIndexRoute
  '/_app/tasks/$taskId/': typeof AppTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/tasks'
    | '/account'
    | '/'
    | '/challenges'
    | '/challenges/$challengeId'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/tasks'
    | '/account'
    | '/'
    | '/challenges'
    | '/challenges/$challengeId'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/tasks'
    | '/_app/account'
    | '/_app/'
    | '/_app/challenges/'
    | '/_app/challenges/$challengeId/'
    | '/_app/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/challenges/': {
      id: '/_app/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AppChallengesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks/$taskId/': {
      id: '/_app/tasks/$taskId/'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdIndexRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    '/_app/challenges/$challengeId/': {
      id: '/_app/challenges/$challengeId/'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof AppChallengesChallengeIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppTasksRouteRouteChildren {
  AppTasksTaskIdIndexRoute: typeof AppTasksTaskIdIndexRoute
}

const AppTasksRouteRouteChildren: AppTasksRouteRouteChildren = {
  AppTasksTaskIdIndexRoute: AppTasksTaskIdIndexRoute,
}

const AppTasksRouteRouteWithChildren = AppTasksRouteRoute._addFileChildren(
  AppTasksRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppTasksRouteRoute: typeof AppTasksRouteRouteWithChildren
  AppAccountRoute: typeof AppAccountRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChallengesIndexRoute: typeof AppChallengesIndexRoute
  AppChallengesChallengeIdIndexRoute: typeof AppChallengesChallengeIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppTasksRouteRoute: AppTasksRouteRouteWithChildren,
  AppAccountRoute: AppAccountRoute,
  AppIndexRoute: AppIndexRoute,
  AppChallengesIndexRoute: AppChallengesIndexRoute,
  AppChallengesChallengeIdIndexRoute: AppChallengesChallengeIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
