name: Trigger Redeploy

on:
  # run whenever a new maproulette/maproulette-frontend package is published to GHCR
  registry_package:
    types: [published]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Send trigger-workflow webhook to maproulette-deploy repository
        run: |
          curl -L \
            -X POST \
            https://api.github.com/repos/maproulette/maproulette-deploy/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event_type": "trigger-workflow" }'
